[package]
name = "simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openai-rust = "1.5.2"
tokio = { version = "1.39.2", features = ["full"] }
